
GET  http://localhost:3000/

###

GET http://localhost:3000/movies/


###

POST http://localhost:3000/movies/

###

GET http://localhost:3000/movies/46

###

PUT http://localhost:3000/movies/4

###

DELETE http://localhost:3000/movies/4

